apiVersion: apps/v1
kind: Deployment
metadata:
  name: get-promotion-app-graceful
spec:
  replicas: 1
  selector:
    matchLabels:
      app: get-promotion-app-graceful
  template:
    metadata:
      labels:
        app: get-promotion-app-graceful
    spec:
      containers:
        - name: get-promotion-app-graceful
          image: cr.yandex/OMITTED/draft-app-with-graceful3:latest
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8090
            initialDelaySeconds: 10
            periodSeconds: 15
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8090
            initialDelaySeconds: 10
            periodSeconds: 15
            failureThreshold: 3
      terminationGracePeriodSeconds: 60
