apiVersion: v1
kind: Service
metadata:
  name: get-promotion-app-graceful-service
spec:
  type: LoadBalancer
  ports:
    - name: http-port-80
      port: 80
      protocol: TCP
      targetPort: 8080
    - name: http-port-8090
      port: 8090
      protocol: TCP
      targetPort: 8090
  selector:
    app: get-promotion-app-graceful
