apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: cronjobber-role
rules:
  - apiGroups: ['apps']
    resources: ['deployments', 'cronjobs', 'pods', 'deployments/scale']
    verbs: ['create', 'get', 'list', 'watch', 'update', 'patch', 'delete']
