apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cronjobber-rolebinding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: cronjobber
    namespace: default
roleRef:
  kind: Role
  name: cronjobber-role
  apiGroup: rbac.authorization.k8s.io
